### ISSUE TITLE
Cannot upload files because folder 'user_files' is missing at install

### ISSUE THREAD

**Issue by guizmoau** [YunoHost-Apps/overleaf_ynh#11]
### Describe the bug

Cannot upload files because folder 'user_files' is missing at install

### Context

- Hardware: VPS bought online
- YunoHost version: latest stable
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

install app
create new project blank
try to upload a file
error

### Expected behavior

upload file with no error

### Logs

in the log filestore.log in /var/log there is mention of an error regarding the path /home/yunohost.app/overleaf/user_files

### Solution

go in the path /home/yunohost.app/overleaf/
create the folder user_files
apply correct rights

all good

**Comment by Thovi98** [comment]
Fixed by https://github.com/YunoHost-Apps/overleaf_ynh/pull/20


Please reopen if not
