### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by Pentaonia** [YunoHost-Apps/overleaf_ynh#19]
### Describe the bug

The app is not installing. :(

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.4
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no *
- Using, or trying to install package version/branch: 2022.04.23~ynh1

### Steps to reproduce

I just hit install in the webadmin.

### Expected behavior

Working installation.

### Logs

[YunoPaste-Log](https://paste.yunohost.org/raw/bupoyahaki)

**Comment by Thovi98** [comment]
Fixed by https://github.com/YunoHost-Apps/overleaf_ynh/pull/20

Please reopen if not
